<?php

use andy87\yii2\file_crafter\Crafter;

$config = [];

if (YII_ENV_DEV)
{
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => yii\gii\Module::class,
        'generators' => [
            'fileCrafter' => [
                'class' => Crafter::class,
                'params' => [
                    'cache' => [
                        'dir' => '@console/runtime/andy87/yii2-dnk-file-crafter/cache',
                        'ext' => '.json'
                    ],
                    'source' => [
                        'dir' => '@console/runtime/andy87/yii2-dnk-file-crafter/templates/source',
                        'ext' => '.tpl',
                    ],
                    'custom_fields' => [
                        'singular' => 'Ед. число',
                        'plural' => 'Мн. число',
                    ],
                ],
                'templates' => [
                    'common' => [
                        'common/services/ItemService' => 'app/common/services/items/{{PascalCase}}Service',
                        'common/services/repositories/ItemRepository' => 'app/common/services/repositories/{{PascalCase}}Repository',
                        'common/services/providers/ItemProvider' => 'app/common/services/providers/{{PascalCase}}Provider',
                        'common/tests/unit/models/item/ItemTest' => 'app/common/tests/unit/models/{{PascalCase}}Test',
                        'common/tests/unit/services/repositories/ItemRepositoryTest' => 'app/common/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'common/tests/unit/services/providers/ItemProviderTest' => 'app/common/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'common/tests/unit/services/ItemServiceTest' => 'app/common/tests/unit/services/items/{{PascalCase}}ServiceTest',
                    ],
                    'console' => [
                        'console/controllers/ItemController' => 'app/console/controllers/{{PascalCase}}Controller',
                        'console/services/ItemService' => 'app/console/services/items/{{PascalCase}}Service',
                        'console/services/repositories/ItemRepository' => 'app/console/services/repositories/{{PascalCase}}Repository',
                        'console/services/providers/ItemProvider' => 'app/console/services/providers/{{PascalCase}}Provider',
                        'console/tests/unit/services/repositories/ItemRepositoryTest' => 'app/console/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'console/tests/unit/services/providers/ItemProviderTest' => 'app/console/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'console/tests/unit/services/ItemServiceTest' => 'app/console/tests/unit/services/items/{{PascalCase}}ServiceTest',
                    ],
                    'frontend' => [
                        'frontend/controllers/ItemController' => 'app/frontend/controllers/{{PascalCase}}Controller',
                        'frontend/resources/ItemIndexResource' => 'app/frontend/resources/{{PascalCase}}IndexResource',
                        'frontend/resources/ItemViewResource' => 'app/frontend/resources/{{PascalCase}}ViewResource',
                        'frontend/views/item/index' => 'app/frontend/views/{{snake_case}}/index',
                        'frontend/views/item/view' => 'app/frontend/views/{{snake_case}}/view',
                        'frontend/services/ItemService' => 'app/frontend/services/items/{{PascalCase}}Service',
                        'frontend/services/repositories/ItemRepository' => 'app/frontend/services/repositories/{{PascalCase}}Repository',
                        'frontend/services/providers/ItemProvider' => 'app/frontend/services/providers/{{PascalCase}}Provider',
                        'frontend/tests/unit/models/item/ItemTest' => 'app/frontend/tests/unit/models/{{PascalCase}}Test',
                        'frontend/tests/unit/services/repositories/ItemRepositoryTest' => 'app/frontend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'frontend/tests/unit/services/providers/ItemProviderTest' => 'app/frontend/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'frontend/tests/unit/services/ItemServiceTest' => 'app/frontend/tests/unit/services/items/{{PascalCase}}ServiceTest',
                        'frontend/tests/unit/resources/ItemIndexResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}IndexResourceTest',
                        'frontend/tests/unit/resources/ItemViewResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}ViewResourceTest',
                        'frontend/tests/functional/ItemControllerCest' => 'app/frontend/tests/functional/{{PascalCase}}ControllerCest',
                        'frontend/tests/acceptance/ItemControllerCest' => 'app/frontend/tests/acceptance/{{PascalCase}}ControllerCest',
                    ],
                    'backend' => [
                        'backend/controllers/ItemController' => 'app/backend/controllers/{{PascalCase}}Controller',
                        'backend/resources/ItemIndexResource' => 'app/backend/resources/{{PascalCase}}IndexResource',
                        'backend/resources/ItemViewResource' => 'app/backend/resources/{{PascalCase}}ViewResource',
                        'backend/resources/ItemFormResource' => 'app/backend/resources/{{PascalCase}}FormResource',
                        'backend/resources/ItemSearchResource' => 'app/backend/resources/{{PascalCase}}SearchResource',
                        'backend/resources/ItemCreateResource' => 'app/backend/resources/{{PascalCase}}CreateResource',
                        'backend/resources/ItemUpdateResource' => 'app/backend/resources/{{PascalCase}}UpdateResource',
                        'backend/views/item/index' => 'app/backend/views/{{snake_case}}/index',
                        'backend/views/item/view' => 'app/backend/views/{{snake_case}}/view',
                        'backend/views/item/form' => 'app/backend/views/{{snake_case}}/form',
                        'backend/views/item/search' => 'app/backend/views/{{snake_case}}/search',
                        'backend/views/item/create' => 'app/backend/views/{{snake_case}}/create',
                        'backend/views/item/update' => 'app/backend/views/{{snake_case}}/update',
                        'backend/services/ItemService' => 'app/backend/services/items/{{PascalCase}}Service',
                        'backend/services/repositories/ItemRepository' => 'app/backend/services/repositories/{{PascalCase}}Repository',
                        'backend/services/providers/ItemProvider' => 'app/backend/services/providers/{{PascalCase}}Provider',
                        'backend/tests/unit/models/item/ItemTest' => 'app/backend/tests/unit/models/{{PascalCase}}Test',
                        'backend/tests/unit/services/repositories/ItemRepositoryTest' => 'app/backend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'backend/tests/unit/services/providers/ItemProviderTest' => 'app/backend/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'backend/tests/unit/services/ItemServiceTest' => 'app/backend/tests/unit/services/items/{{PascalCase}}ServiceTest',
                        'backend/tests/unit/resources/ItemIndexResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}IndexResourceTest',
                        'backend/tests/unit/resources/ItemViewResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}ViewResourceTest',
                        'backend/tests/unit/resources/ItemFormResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}FormResourceTest',
                        'backend/tests/unit/resources/ItemSearchResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}SearchResourceTest',
                        'backend/tests/unit/resources/ItemCreateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}CreateResourceTest',
                        'backend/tests/unit/resources/ItemUpdateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}UpdateResourceTest',
                        'backend/tests/functional/ItemControllerCest' => 'app/backend/tests/functional/{{PascalCase}}ControllerCest',
                        'backend/tests/acceptance/ItemControllerCest' => 'app/backend/tests/acceptance/{{PascalCase}}ControllerCest',
                    ],
                    'all' => [
                        'common/services/ItemService' => 'app/common/services/items/{{PascalCase}}Service',
                        'common/services/repositories/ItemRepository' => 'app/common/services/repositories/{{PascalCase}}Repository',
                        'common/services/providers/ItemProvider' => 'app/common/services/providers/{{PascalCase}}Provider',
                        'common/tests/unit/models/item/ItemTest' => 'app/common/tests/unit/models/{{PascalCase}}Test',
                        'common/tests/unit/services/repositories/ItemRepositoryTest' => 'app/common/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'common/tests/unit/services/providers/ItemProviderTest' => 'app/common/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'common/tests/unit/services/ItemServiceTest' => 'app/common/tests/unit/services/items/{{PascalCase}}ServiceTest',

                        'console/controllers/ItemController' => 'app/console/controllers/{{PascalCase}}Controller',
                        'console/services/ItemService' => 'app/console/services/items/{{PascalCase}}Service',
                        'console/services/repositories/ItemRepository' => 'app/console/services/repositories/{{PascalCase}}Repository',
                        'console/services/providers/ItemProvider' => 'app/console/services/providers/{{PascalCase}}Provider',
                        'console/tests/unit/services/repositories/ItemRepositoryTest' => 'app/console/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'console/tests/unit/services/providers/ItemProviderTest' => 'app/console/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'console/tests/unit/services/ItemServiceTest' => 'app/console/tests/unit/services/items/{{PascalCase}}ServiceTest',

                        'frontend/controllers/ItemController' => 'app/frontend/controllers/{{PascalCase}}Controller',
                        'frontend/resources/ItemIndexResource' => 'app/frontend/resources/{{PascalCase}}IndexResource',
                        'frontend/resources/ItemViewResource' => 'app/frontend/resources/{{PascalCase}}ViewResource',
                        'frontend/views/item/index' => 'app/frontend/views/{{snake_case}}/index',
                        'frontend/views/item/view' => 'app/frontend/views/{{snake_case}}/view',
                        'frontend/services/ItemService' => 'app/frontend/services/items/{{PascalCase}}Service',
                        'frontend/services/repositories/ItemRepository' => 'app/frontend/services/repositories/{{PascalCase}}Repository',
                        'frontend/services/providers/ItemProvider' => 'app/frontend/services/providers/{{PascalCase}}Provider',
                        'frontend/tests/unit/models/item/ItemTest' => 'app/frontend/tests/unit/models/{{PascalCase}}Test',
                        'frontend/tests/unit/services/repositories/ItemRepositoryTest' => 'app/frontend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'frontend/tests/unit/services/providers/ItemProviderTest' => 'app/frontend/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'frontend/tests/unit/services/ItemServiceTest' => 'app/frontend/tests/unit/services/items/{{PascalCase}}ServiceTest',
                        'frontend/tests/unit/resources/ItemIndexResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}IndexResourceTest',
                        'frontend/tests/unit/resources/ItemViewResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}ViewResourceTest',
                        'frontend/tests/functional/ItemControllerCest' => 'app/frontend/tests/functional/{{PascalCase}}ControllerCest',
                        'frontend/tests/acceptance/ItemControllerCest' => 'app/frontend/tests/acceptance/{{PascalCase}}ControllerCest',

                        'backend/controllers/ItemController' => 'app/backend/controllers/{{PascalCase}}Controller',
                        'backend/resources/ItemIndexResource' => 'app/backend/resources/{{PascalCase}}IndexResource',
                        'backend/resources/ItemViewResource' => 'app/backend/resources/{{PascalCase}}ViewResource',
                        'backend/resources/ItemFormResource' => 'app/backend/resources/{{PascalCase}}FormResource',
                        'backend/resources/ItemSearchResource' => 'app/backend/resources/{{PascalCase}}SearchResource',
                        'backend/resources/ItemCreateResource' => 'app/backend/resources/{{PascalCase}}CreateResource',
                        'backend/resources/ItemUpdateResource' => 'app/backend/resources/{{PascalCase}}UpdateResource',
                        'backend/views/item/index' => 'app/backend/views/{{snake_case}}/index',
                        'backend/views/item/view' => 'app/backend/views/{{snake_case}}/view',
                        'backend/views/item/form' => 'app/backend/views/{{snake_case}}/form',
                        'backend/views/item/search' => 'app/backend/views/{{snake_case}}/search',
                        'backend/views/item/create' => 'app/backend/views/{{snake_case}}/create',
                        'backend/views/item/update' => 'app/backend/views/{{snake_case}}/update',
                        'backend/services/ItemService' => 'app/backend/services/items/{{PascalCase}}Service',
                        'backend/services/repositories/ItemRepository' => 'app/backend/services/repositories/{{PascalCase}}Repository',
                        'backend/services/providers/ItemProvider' => 'app/backend/services/providers/{{PascalCase}}Provider',
                        'backend/tests/unit/models/item/ItemTest' => 'app/backend/tests/unit/models/{{PascalCase}}Test',
                        'backend/tests/unit/services/repositories/ItemRepositoryTest' => 'app/backend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
                        'backend/tests/unit/services/providers/ItemProviderTest' => 'app/backend/tests/unit/services/providers/{{PascalCase}}ProviderTest',
                        'backend/tests/unit/services/ItemServiceTest' => 'app/backend/tests/unit/services/items/{{PascalCase}}ServiceTest',
                        'backend/tests/unit/resources/ItemIndexResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}IndexResourceTest',
                        'backend/tests/unit/resources/ItemViewResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}ViewResourceTest',
                        'backend/tests/unit/resources/ItemFormResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}FormResourceTest',
                        'backend/tests/unit/resources/ItemSearchResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}SearchResourceTest',
                        'backend/tests/unit/resources/ItemCreateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}CreateResourceTest',
                        'backend/tests/unit/resources/ItemUpdateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}UpdateResourceTest',
                        'backend/tests/functional/ItemControllerCest' => 'app/backend/tests/functional/{{PascalCase}}ControllerCest',
                        'backend/tests/acceptance/ItemControllerCest' => 'app/backend/tests/acceptance/{{PascalCase}}ControllerCest',
                    ],
                ],
            ],
        ],
    ];
}

return $config;