<?php

/**
 * Full separated mapping for the file crafter generator.
 */

return [
    'common' => [
        'common/services/ItemService' => 'app/common/services/items/{{PascalCase}}Service',
        'common/services/ItemRepository' => 'app/common/services/repositories/{{PascalCase}}Repository',
        'common/services/ItemProvider' => 'app/common/services/providers/{{PascalCase}}Provider',
        'common/tests/unit/models/items/ItemTest' => 'app/common/tests/unit/models/{{PascalCase}}Test',
        'common/tests/unit/services/ItemRepositoryTest' => 'app/common/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
        'common/tests/unit/services/ItemProviderTest' => 'app/common/tests/unit/services/providers/{{PascalCase}}ProviderTest',
        'common/tests/unit/services/ItemServiceTest' => 'app/common/tests/unit/services/items/{{PascalCase}}ServiceTest',
    ],
    'console' => [
        'console/ItemController' => 'app/console/controllers/{{PascalCase}}Controller',
        'console/services/ItemService' => 'app/console/services/items/{{PascalCase}}Service',
        'console/services/ItemRepository' => 'app/console/services/repositories/{{PascalCase}}Repository',
        'console/services/ItemProvider' => 'app/console/services/providers/{{PascalCase}}Provider',
        'console/tests/unit/services/ItemRepositoryTest' => 'app/console/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
        'console/tests/unit/services/ItemProviderTest' => 'app/console/tests/unit/services/providers/{{PascalCase}}ProviderTest',
        'console/tests/unit/services/ItemServiceTest' => 'app/console/tests/unit/services/items/{{PascalCase}}ServiceTest',
    ],
    'frontend' => [
        'frontend/ItemController' => 'app/frontend/controllers/{{PascalCase}}Controller',
        'frontend/resources/ItemIndexResource' => 'app/frontend/resources/{{PascalCase}}IndexResource',
        'frontend/resources/ItemViewResource' => 'app/frontend/resources/{{PascalCase}}ViewResource',
        'frontend/views/index' => 'app/frontend/views/{{snake_case}}/index',
        'frontend/views/view' => 'app/frontend/views/{{snake_case}}/view',
        'frontend/services/ItemService' => 'app/frontend/services/items/{{PascalCase}}Service',
        'frontend/services/ItemRepository' => 'app/frontend/services/repositories/{{PascalCase}}Repository',
        'frontend/services/ItemProvider' => 'app/frontend/services/providers/{{PascalCase}}Provider',
        'frontend/tests/unit/models/ItemTest' => 'app/frontend/tests/unit/models/{{PascalCase}}Test',
        'frontend/tests/unit/services/ItemRepositoryTest' => 'app/frontend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
        'frontend/tests/unit/services/ItemProviderTest' => 'app/frontend/tests/unit/services/providers/{{PascalCase}}ProviderTest',
        'frontend/tests/unit/services/ItemServiceTest' => 'app/frontend/tests/unit/services/items/{{PascalCase}}ServiceTest',
        'frontend/tests/unit/resources/ItemIndexResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}IndexResourceTest',
        'frontend/tests/unit/resources/ItemViewResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}ViewResourceTest',
        'frontend/tests/functional/ItemControllerCest' => 'app/frontend/tests/functional/{{PascalCase}}ControllerCest',
        'frontend/tests/acceptance/ItemControllerCest' => 'app/frontend/tests/acceptance/{{PascalCase}}ControllerCest',
    ],
    'backend' => [
        'backend/ItemController' => 'app/backend/controllers/{{PascalCase}}Controller',
        'backend/resources/ItemIndexResource' => 'app/backend/resources/{{PascalCase}}IndexResource',
        'backend/resources/ItemViewResource' => 'app/backend/resources/{{PascalCase}}ViewResource',
        'backend/resources/ItemFormResource' => 'app/backend/resources/{{PascalCase}}FormResource',
        'backend/resources/ItemSearchResource' => 'app/backend/resources/{{PascalCase}}SearchResource',
        'backend/resources/ItemCreateResource' => 'app/backend/resources/{{PascalCase}}CreateResource',
        'backend/resources/ItemUpdateResource' => 'app/backend/resources/{{PascalCase}}UpdateResource',
        'backend/views/index' => 'app/backend/views/{{snake_case}}/index',
        'backend/views/view' => 'app/backend/views/{{snake_case}}/view',
        'backend/views/form' => 'app/backend/views/{{snake_case}}/form',
        'backend/views/search' => 'app/backend/views/{{snake_case}}/search',
        'backend/views/create' => 'app/backend/views/{{snake_case}}/create',
        'backend/views/update' => 'app/backend/views/{{snake_case}}/update',
        'backend/services/ItemService' => 'app/backend/services/items/{{PascalCase}}Service',
        'backend/services/ItemRepository' => 'app/backend/services/repositories/{{PascalCase}}Repository',
        'backend/services/ItemProvider' => 'app/backend/services/providers/{{PascalCase}}Provider',
        'backend/tests/unit/models/items/ItemTest' => 'app/backend/tests/unit/models/{{PascalCase}}Test',
        'backend/tests/unit/services/ItemRepositoryTest' => 'app/backend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest',
        'backend/tests/unit/services/ItemProviderTest' => 'app/backend/tests/unit/services/providers/{{PascalCase}}ProviderTest',
        'backend/tests/unit/services/ItemServiceTest' => 'app/backend/tests/unit/services/items/{{PascalCase}}ServiceTest',
        'backend/tests/unit/resources/ItemIndexResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}IndexResourceTest',
        'backend/tests/unit/resources/ItemViewResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}ViewResourceTest',
        'backend/tests/unit/resources/ItemFormResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}FormResourceTest',
        'backend/tests/unit/resources/ItemSearchResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}SearchResourceTest',
        'backend/tests/unit/resources/ItemCreateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}CreateResourceTest',
        'backend/tests/unit/resources/ItemUpdateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}UpdateResourceTest',
        'backend/tests/functional/ItemControllerCest' => 'app/backend/tests/functional/{{PascalCase}}ControllerCest',
        'backend/tests/acceptance/ItemControllerCest' => 'app/backend/tests/acceptance/{{PascalCase}}ControllerCest',
    ],
];