<?php

/**
 * Full separated mapping for the file crafter generator.
 */

return [
    'common' => [
        'common/services/ItemService' => 'app/common/services/items/{{PascalCase}}Service.php',
        'common/services/ItemRepository' => 'app/common/services/repositories/{{PascalCase}}Repository.php',
        'common/services/ItemProvider' => 'app/common/services/providers/{{PascalCase}}Provider.php',
        'common/tests/unit/models/items/ItemTest' => 'app/common/tests/unit/models/{{PascalCase}}Test.php',
        'common/tests/unit/services/ItemRepositoryTest' => 'app/common/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'common/tests/unit/services/ItemProviderTest' => 'app/common/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'common/tests/unit/services/ItemServiceTest' => 'app/common/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
    ],
    'console' => [
        'console/ItemController' => 'app/console/controllers/{{PascalCase}}Controller.php',
        'console/services/ItemService' => 'app/console/services/items/{{PascalCase}}Service.php',
        'console/services/ItemRepository' => 'app/console/services/repositories/{{PascalCase}}Repository.php',
        'console/services/ItemProvider' => 'app/console/services/providers/{{PascalCase}}Provider.php',
        'console/tests/unit/services/ItemRepositoryTest' => 'app/console/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'console/tests/unit/services/ItemProviderTest' => 'app/console/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'console/tests/unit/services/ItemServiceTest' => 'app/console/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
    ],
    'frontend' => [
        'frontend/ItemController' => 'app/frontend/controllers/{{PascalCase}}Controller.php',
        'frontend/resources/ItemIndexResource' => 'app/frontend/resources/{{PascalCase}}IndexResource.php',
        'frontend/resources/ItemViewResource' => 'app/frontend/resources/{{PascalCase}}ViewResource.php',
        'frontend/views/index' => 'app/frontend/views/{{snake_case}}/index.php',
        'frontend/views/view' => 'app/frontend/views/{{snake_case}}/view.php',
        'frontend/services/ItemService' => 'app/frontend/services/items/{{PascalCase}}Service.php',
        'frontend/services/ItemRepository' => 'app/frontend/services/repositories/{{PascalCase}}Repository.php',
        'frontend/services/ItemProvider' => 'app/frontend/services/providers/{{PascalCase}}Provider.php',
        'frontend/tests/unit/models/ItemTest' => 'app/frontend/tests/unit/models/{{PascalCase}}Test.php',
        'frontend/tests/unit/services/ItemRepositoryTest' => 'app/frontend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'frontend/tests/unit/services/ItemProviderTest' => 'app/frontend/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'frontend/tests/unit/services/ItemServiceTest' => 'app/frontend/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
        'frontend/tests/unit/resources/ItemIndexResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}IndexResourceTest.php',
        'frontend/tests/unit/resources/ItemViewResourceTest' => 'app/frontend/tests/unit/resources/{{PascalCase}}ViewResourceTest.php',
        'frontend/tests/functional/ItemControllerCest' => 'app/frontend/tests/functional/{{PascalCase}}ControllerCest.php',
        'frontend/tests/acceptance/ItemControllerCest' => 'app/frontend/tests/acceptance/{{PascalCase}}ControllerCest.php',
    ],
    'backend' => [
        'backend/ItemController' => 'app/backend/controllers/{{PascalCase}}Controller.php',
        'backend/resources/ItemIndexResource' => 'app/backend/resources/{{PascalCase}}IndexResource.php',
        'backend/resources/ItemViewResource' => 'app/backend/resources/{{PascalCase}}ViewResource.php',
        'backend/resources/ItemFormResource' => 'app/backend/resources/{{PascalCase}}FormResource.php',
        'backend/resources/ItemSearchResource' => 'app/backend/resources/{{PascalCase}}SearchResource.php',
        'backend/resources/ItemCreateResource' => 'app/backend/resources/{{PascalCase}}CreateResource.php',
        'backend/resources/ItemUpdateResource' => 'app/backend/resources/{{PascalCase}}UpdateResource.php',
        'backend/views/index' => 'app/backend/views/{{snake_case}}/index.php',
        'backend/views/view' => 'app/backend/views/{{snake_case}}/view.php',
        'backend/views/form' => 'app/backend/views/{{snake_case}}/form.php',
        'backend/views/search' => 'app/backend/views/{{snake_case}}/search.php',
        'backend/views/create' => 'app/backend/views/{{snake_case}}/create.php',
        'backend/views/update' => 'app/backend/views/{{snake_case}}/update.php',
        'backend/services/ItemService' => 'app/backend/services/items/{{PascalCase}}Service.php',
        'backend/services/ItemRepository' => 'app/backend/services/repositories/{{PascalCase}}Repository.php',
        'backend/services/ItemProvider' => 'app/backend/services/providers/{{PascalCase}}Provider.php',
        'backend/tests/unit/models/items/ItemTest' => 'app/backend/tests/unit/models/{{PascalCase}}Test.php',
        'backend/tests/unit/services/ItemRepositoryTest' => 'app/backend/tests/unit/services/repositories/{{PascalCase}}RepositoryTest.php',
        'backend/tests/unit/services/ItemProviderTest' => 'app/backend/tests/unit/services/providers/{{PascalCase}}ProviderTest.php',
        'backend/tests/unit/services/ItemServiceTest' => 'app/backend/tests/unit/services/items/{{PascalCase}}ServiceTest.php',
        'backend/tests/unit/resources/ItemIndexResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}IndexResourceTest.php',
        'backend/tests/unit/resources/ItemViewResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}ViewResourceTest.php',
        'backend/tests/unit/resources/ItemFormResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}FormResourceTest.php',
        'backend/tests/unit/resources/ItemSearchResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}SearchResourceTest.php',
        'backend/tests/unit/resources/ItemCreateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}CreateResourceTest.php',
        'backend/tests/unit/resources/ItemUpdateResourceTest' => 'app/backend/tests/unit/resources/{{PascalCase}}UpdateResourceTest.php',
        'backend/tests/functional/ItemControllerCest' => 'app/backend/tests/functional/{{PascalCase}}ControllerCest.php',
        'backend/tests/acceptance/ItemControllerCest' => 'app/backend/tests/acceptance/{{PascalCase}}ControllerCest.php',
    ],
];